[project]
src = "src"
out = "out"
dot_env = ".env"
name = "untron-v2"
version = "0.1.0"
description = "Efficiency-centric alternative to Untron V1, a P2P swapper from Tron"
requires-python = ">=3.10"
keywords = [
  "security",
  "library",
  "ethereum",
  "smart-contracts",
  "evm",
  "vyper",
  "vyper-contracts",
]
authors = [
  { name = "Ultrasound Labs", email = "contact@ultrasoundlabs.org" },
]
maintainers = [
  { name = "Ultrasound Labs", email = "contact@ultrasoundlabs.org" },
]
dependencies = ["pcaversaccio/snekmate"]

[project.readme]
file = "README.md"
content-type = "text/markdown"
[project.license]
text = "MIT License"
[project.urls]
Homepage = "https://github.com/ultrasoundlabs/untron-v2#readme"
GitHub = "https://github.com/ultrasoundlabs/untron-v2"
Changelog = "https://github.com/ultrasoundlabs/untron-v2/blob/main/CHANGELOG.md"

[networks.pyevm]
is_zksync = false

[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
save_to_db = false
chain_id = 31337

[networks.sepolia]
url = "https://ethereum-sepolia-rpc.publicnode.com"
chain_id = 11155111

[networks.base]
url = "https://mainnet.base.org"
chain_id = 8453

[networks.base-sepolia]
url = "https://sepolia.base.org"
chain_id = 84532

[networks.arbitrum]
url = "https://arb1.arbitrum.io/rpc"
chain_id = 42161

[networks.zksync-sepolia]
url = "https://sepolia.era.zksync.dev"
chain_id = 300
is_zksync = true
prompt_live = true

[networks.contracts]
UntronV2 = {  deployer_script = "deploy.py" }

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
